### ISSUE TITLE
Test method

### ISSUE THREAD

**Issue by ybbwcwaps** [Michel-liu/FatFormer#1]
I have a question, because you don't have open source yet. After reading the paper, I don't understand, when detecting whether an image is a synthetic, only the image needs to be input, or the corresponding text of the image is needed?

**Comment by Michel-liu** [comment]
Sorry for the delayed reply. During testing, FatFormer only requires images as the input. Although the text branch is needed to calculate the final similarity, the text prompt input is fixed after training, just like the pre-trained parameters. BTW, the code is under internal review and will be released in the next two months. Thanks for your interest in our work.
