### ISSUE TITLE
Some questions about the FAA module and LGA module

### ISSUE THREAD

**Issue by taoxinhao13** [Michel-liu/FatFormer#3]
Hello,
Your paper is truly impressive. However, the structures of both the FAA module and LGA module are rather intricate. I have already reached out to you via email, and I was wondering if it would be possible for you to provide a simplified version of the implementations for these two modules. Your assistance would be greatly appreciated.

**Comment by Michel-liu** [comment]
Thanks for your interest in our FatFormer. We have uploaded the code, and you can check the implementation now. If you have further questions, welcome to reopen this issue.
