### ISSUE TITLE
Test Dataset Problem

### ISSUE THREAD

**Issue by maliarabaci** [Michel-liu/FatFormer#5]
I want to replicate the results for different GAN and Diffusion-based generator. However, download links are dead. Do you have a plan to release test dataset ?

**Comment by Michel-liu** [comment]
Thanks for your interest in our work. We have updated the onedrive links of test datasets.

**Comment by maliarabaci** [comment]
Thanks Michel for your quick reply. I've successfully downloaded test datasets using OneDrive links. However, both DM_testdata.zip and GAN_testdata.zip files are corrupted. Unfortunately, I could only partially extract the files from zip format. Healthy folder are the followings: GAN_testdata->CycleGAN, DM_testdata->dalle, DM_testdata->Glide_50_27, DM_testdata->Glide_100_10, DM_testdata->ldm_100, DM_testdata->ldm_200_cfg, DM_testdata->pndm, and DM_testdata->vqdiffusion.

All the files from other folders can not be extracted from the zip files. Could you please check the health status of the zip files that you uploaded to OneDrive?

**Comment by Michel-liu** [comment]
I didn't meet your problem, please re-download them and check the md5 for GAN data `949469cc600111b609bedadf8b15cbf3` and DM data `0c3bbb4dcb66fdcad424694e87060f06`.
